### ISSUE TITLE
进一步减少服务器开支，防止滥用。

### ISSUE THREAD

**Issue by dylanbai8** [bclswl0827/v2ray-heroku#1]
感谢分享。一些使用心得：

客户端 1.关闭“tls传输底层安全”（使用80端口），2.关闭加密方式，选择“none”，3.额外id尽量小的值，比如“2”。

可以进一步减少服务器开支，防止滥用。

**Comment by bclswl0827** [comment]
关于您的问题，下面是我的回复：

 - 关闭 TLS 意味着你的所有通信将会轻易被火墙识别，虽然可以减少 TLS 握手的延时，但是真的不推荐像这样裸奔...
 - 不同于 Shadowsocks，V2Ray 的加密是在本地进行的，而非服务器上，所以不存在“耗费服务器资源”这种说法。此外，一些处理器对于一些加密方式有着硬件支持，在本地启用加密可以在一定程度上起到加速之作用。可以参考 https://steemit.com/cn/@v2ray/3cjiux
 - 有关 AlterID 倒可以考虑选用更小的值，以节省开支。

感谢您的关注！

**Comment by bclswl0827** [comment]
Closed.
