### ISSUE TITLE
无法连接

### ISSUE THREAD

**Issue by huangshi10492** [bclswl0827/v2ray-heroku#10]
在clash和v2rayN上均无法连接上
![2{2G%%2G3DGDGAKUQG4GXKE](https://user-images.githubusercontent.com/42275197/77766531-bac4c480-707a-11ea-82c3-795635776fba.png)
网址可访问

**Comment by goodJackSong** [comment]
连不上啊

**Comment by bclswl0827** [comment]
代码没有问题，是你们客户端配置问题

**Comment by ntgeralt** [comment]
直接部署后，
![Desktop Screenshot 2020 04 03 - 06 50 52 64](https://user-images.githubusercontent.com/8230651/78307034-8029c300-7577-11ea-9473-2affd1092bfc.png)
这样无法连接。我也不知道有没有填错。

这时候配合用cf反代，
https://www.529i.com/archives/772.html
改成cf域名就连接上了. 我也不知道怎么解决……

**Comment by yangluom** [comment]
大佬，我也出现了类似的现象，成功部署了，但是不能够连接，是不是需要个反代？？

**Comment by ntgeralt** [comment]
试过搭建后大半天无法连接；隔一天再又能联通。参数正确的话隔一阵再测。
