### ISSUE TITLE
请教添加path方式

### ISSUE THREAD

**Issue by ntgeralt** [bclswl0827/v2ray-heroku#12]
想做个均衡负载，和别的v2放一起。需要改成path一致。我添加PATH变量似乎不奏效，这里请教下正确方式。

**Comment by bclswl0827** [comment]
变量名称 `PATH` 请改成其他的名字试试，比如 `V2RAY_PATH`

**Comment by ntgeralt** [comment]
@bclswl0827 won't work.I think i just give up..
