### ISSUE TITLE
參數修改後部署至Heroku

### ISSUE THREAD

**Issue by rootmelo92118** [bclswl0827/v2ray-heroku#16]
小弟我把此倉庫clone一份至https://github.com/secret-factory/v2ray-heroku-edit-from-bclswl0827
但從Heroku拉取Github倉庫部署時
卻無法正常啟動Heroku
V2ray錯誤信息為I/O read/write on closed pipes.

**Comment by bclswl0827** [comment]
直接訪問 Heroku 分配的二級域名时，會出現 400 Bad request 字樣嗎

**Comment by rootmelo92118** [comment]
> 直接訪問 Heroku 分配的二級域名时，會出現 400 Bad request 字樣嗎

是

**Comment by rootmelo92118** [comment]
> 直接訪問 Heroku 分配的二級域名时，會出現 400 Bad request 字樣嗎

不會

**Comment by bclswl0827** [comment]
直接訪問域名，如果沒有出現 Bad Request 字樣，這就意味着部署失敗了
你有試過重新部署嗎？

**Comment by rootmelo92118** [comment]
> 直接訪問域名，如果沒有出現 Bad Request 字樣，這就意味着部署失敗了
> 你有試過重新部署嗎？

有的

**Comment by bclswl0827** [comment]
能否提供一份日誌供參考呢？
![20200522162305](https://user-images.githubusercontent.com/24319042/82647283-8cadcc00-9c48-11ea-8dc2-4dec7838554d.jpg)

**Comment by rootmelo92118** [comment]
![Screenshot_2020-05-24-14-14-28-774_com android chrome](https://user-images.githubusercontent.com/32770959/82747143-f523b700-9dc8-11ea-8f67-c79ffb624e6f.jpg)

**Comment by bclswl0827** [comment]
請嘗試使用本倉庫進行部署
