### ISSUE TITLE
能帮我看了下

### ISSUE THREAD

**Issue by whhxmwhh** [bclswl0827/v2ray-heroku#2]
port用多少？
deploy以后还需要怎么设置？
能显示“Bad Request”

**Comment by bclswl0827** [comment]
你什么都不用做
只需要按下 README 中的部署按钮即可部署
填入 UUID，稍等片刻，即可部署成功，探测所分配域名的 / 路径，即可看到 400 返回码
这份代码已经测试成功，且不会导致封号，可以放心使用

**Comment by whhxmwhh** [comment]
端口是多少？

![ask捕获](https://user-images.githubusercontent.com/7959854/69198820-061d1280-0b71-11ea-9204-4cf6eb835a1c.JPG)
感谢。。这些有些需要填写的这里找不到说明。男帮我看看？

**Comment by bclswl0827** [comment]
域名是 Heroku 分配给你的，不带 HTTPS 前缀，端口 443，UUID 是你自己定义的，额外 ID 是 64，路径是 /
其他保持默认

**Comment by whhxmwhh** [comment]
感谢！

**Comment by colemanlee** [comment]
> 域名是 Heroku 分配给你的，不带 HTTPS 前缀，端口 443，UUID 是你自己定义的，额外 ID 是 64，路径是 /
> 其他保持默认

按照这个配置能够正常使用了，建议将如下配置信息写在Readme里供大家参考：
```
address: ***.herokuapp.com
port:443
id:系统分配的
alterId：64
security:auto
network:ws
remarks:任意填写
type:none
host:留空白
path:/
传输层安全：tls
allowInsecure:true
```

**Comment by bclswl0827** [comment]
> > 域名是 Heroku 分配给你的，不带 HTTPS 前缀，端口 443，UUID 是你自己定义的，额外 ID 是 64，路径是 /
> > 其他保持默认
> 
> 按照这个配置能够正常使用了，建议将如下配置信息写在Readme里供大家参考：
> 
> ```
> address: ***.herokuapp.com
> port:443
> id:系统分配的
> alterId：64
> security:auto
> network:ws
> remarks:任意填写
> type:none
> host:留空白
> path:/
> 传输层安全：tls
> allowInsecure:true
> ```

这个是在 V2RayN 的设置，不是 v2ray 的原始配置文件，不太标准

**Comment by colemanlee** [comment]
> > > 域名是 Heroku 分配给你的，不带 HTTPS 前缀，端口 443，UUID 是你自己定义的，额外 ID 是 64，路径是 /
> > > 其他保持默认
> > 
> > 
> > 按照这个配置能够正常使用了，建议将如下配置信息写在Readme里供大家参考：
> > ```
> > address: ***.herokuapp.com
> > port:443
> > id:系统分配的
> > alterId：64
> > security:auto
> > network:ws
> > remarks:任意填写
> > type:none
> > host:留空白
> > path:/
> > 传输层安全：tls
> > allowInsecure:true
> > ```
> 
> 这个是在 V2RayN 的设置，不是 v2ray 的原始配置文件，不太标准

好的。
