### ISSUE TITLE
Vless 协定支持

### ISSUE THREAD

**Issue by hostlocer** [bclswl0827/v2ray-heroku#26]
VLESS 协议支持

**Comment by bclswl0827** [comment]
[github.com/bclswl0827/v2ray-heroku/tree/vless](https://github.com/bclswl0827/v2ray-heroku/tree/vless)

已经加上了对 Vless 的支持，请测试并反馈。

**Comment by hostlocer** [comment]
之前已经试过改 config（改法和你的一样），和 VMess 版本相比没有明显的速度提升，在部分 Android 设备上使用 v2rayNG 客户端时 Chrome 访问网页出现 DNS_PROBE_FINISHED_NO_INTERNET 错误，感觉 VLESS 还不稳定所以 issue 改成 Ignore 了

**Comment by 882100** [comment]
建议Vless的配置文件默认使用TCP协议而不是WS协议，实测转发性能会好很多。
