### ISSUE TITLE
搭建问题请教

### ISSUE THREAD

**Issue by misshyh** [bclswl0827/v2ray-heroku#36]
您好，按照您添加的部署按钮部署到heroku上面后，V2rayz中测试延时为200ms左右，测试速度为1.8M左右，设置为活服务器后连Google都还不能进，YouTube也打不开，ping都是超时。想问下这可能是什么问题，或者是本身heroku上面做了限制？

**Comment by pestxxo** [comment]
优先cloudflareIP，做反代和IBM那个一样的代码

**Comment by misshyh** [comment]
> 优先cloudflareIP，做反代和IBM那个一样的代码，可以起飞~

做了cloudflareIP，就是上不了Google，YouTube也不行

**Comment by pestxxo** [comment]
不应该啊，PING是PING不通的，不影响使用，GOOGLE很快的

**Comment by misshyh** [comment]
我也就只能在v2ray上面测一下速度 感觉很快很刺激 ，就是上。。
可否远程看一下

**Comment by pestxxo** [comment]
![image](https://user-images.githubusercontent.com/58849942/100432303-62940580-30d4-11eb-8d6c-b026038a614d.png)
你和我的对比下

**Comment by misshyh** [comment]
额外ID 设的64  allowinsecure设置的true其他都一样

**Comment by misshyh** [comment]
![1](https://user-images.githubusercontent.com/29188880/100433095-873cad00-30d5-11eb-8011-1007c5dc37f5.png)
![2](https://user-images.githubusercontent.com/29188880/100433099-87d54380-30d5-11eb-8299-0cfaba6e4e33.png)

**Comment by misshyh** [comment]
对比了其他的，设置活服务器后，软件下方的HTTP 显示的是OFF

**Comment by pestxxo** [comment]
应该可以了，你改成全局试下GOOGLE

**Comment by misshyh** [comment]
我今天去实验室试试，搞了好几天都没进展，太惨了





------------------ 原始邮件 ------------------
发件人: pestxxo <notifications@github.com&gt;
发送时间: 2020年11月27日 17:46
收件人: bclswl0827/v2ray-heroku <v2ray-heroku@noreply.github.com&gt;
抄送: misshyh <1290952376@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[bclswl0827/v2ray-heroku] 搭建问题请教 (#36)





 
应该可以了，你改成全局试下GOOGLE

**Comment by bclswl0827** [comment]
> 不应该啊，PING是PING不通的，不影响使用，GOOGLE很快的

heroku 禁 ping 的

**Comment by misshyh** [comment]
![3](https://user-images.githubusercontent.com/29188880/100491981-20fe6b80-3163-11eb-9374-4605c3b98acb.png)
改了这个全局代理，GitHub都打不开了。。

**Comment by misshyh** [comment]
感谢各位，问题在打开http全局代理过后就解决了。
