### ISSUE TITLE
希望升级成Xray

### ISSUE THREAD

**Issue by HKMV** [bclswl0827/v2ray-heroku#47]
最近新出的Xray性能不错，希望升级成Xray。

**Comment by bclswl0827** [comment]
可以考虑另外做一个 xray 的专案，这个专案也保留

**Comment by playnetcn** [comment]
@bclswl0827 两套方案最好，一个项目部署v2ray,一个项目部署Xray。

**Comment by liuhongzhe111** [comment]
啥时候出Xray的？翘首以盼呢。

**Comment by HKMV** [comment]
> 可以考虑另外做一个 xray 的专案，这个专案也保留

期待
