### ISSUE TITLE
作者，我提个建议，你们觉得怎么样？

### ISSUE THREAD

**Issue by lili205** [bclswl0827/v2ray-heroku#52]
首先谢谢作者的辛苦付出，我是刚刚学会搭建vps的，感谢heroku让我们能白嫖，让我享受到了很长一段时间的稳定的科学上网，我的建议是，对于绝大部分人来说能翻墙出来也就是看看YouTube，看看新闻而已，所以对于网速来说，不需要能看4k，2k，甚至1080p都不需要，能看720p就够了，所以的我的建议就是能不能限制一下网速呢？稳定才是王道啊，能安安稳稳的用很久就比啥都强。

**Comment by ldj-network** [comment]
> 首先谢谢作者的辛苦付出，我是刚刚学会搭建vps的，感谢heroku让我们能白嫖，让我享受到了很长一段时间的稳定的科学上网，我的建议是，对于绝大部分人来说能翻墙出来也就是看看YouTube，看看新闻而已，所以对于网速来说，不需要能看4k，2k，甚至1080p都不需要，能看720p就够了，所以的我的建议就是能不能限制一下网速呢？稳定才是王道啊，能安安稳稳的用很久就比啥都强。

这个还是看自己自觉吧，就算限制了，还是可以是**GitHub**上找到替代的，而且，大部分是使用**CDN**加速，不过_滥用_的话，最后，大家都不能玩了。。。且用且珍惜。。。

**Comment by xkh01** [comment]
## 限制网速可以通过客户端进行达到，你想要的结果是实现不了的，这个库就是只安装v2ray到heroku，并不会做一些改动，如果你愿意，也可以直接改app的文件。

**Comment by bclswl0827** [comment]
你可以自己修改 Dockerfile，安装 `trickle`，然后用 `trickle` 命令来限制 V2Ray 的速度。
但是 Alpine Linux 软件仓库没有内建 trickle，你可能要自己编译一下
