### ISSUE TITLE
想要Xray

### ISSUE THREAD

**Issue by xkh01** [bclswl0827/v2ray-heroku#56]
### 最近出了个Xray，性能挺好，能不能弄一个？

**Comment by bclswl0827** [comment]
最近满忙的，六月份来吧，专案已经建好了

**Comment by bclswl0827** [comment]
> 最近满忙的，六月份来吧，专案已经建好了

https://github.com/search?q=heroku+xray
就不重复造轮子了，GitHub 上这样的专案一大堆，平时也没什么时间来维护
