### ISSUE TITLE
Heroku上部署的v2ray突然不能用了

### ISSUE THREAD

**Issue by gittig11** [bclswl0827/v2ray-heroku#60]
2021.6.18发现，之前部署的v2ray应用连接不上，后来登录 [官网](https://dashboard.heroku.com/apps)，看到服务挂掉了。
![heroku](https://raw.githubusercontent.com/gittig11/pic-cloud-repo/main/heroku%E6%9C%8D%E5%8A%A1%E6%8C%82%E6%8E%89.png)
```heroku logs``` 查看日志未发现异常。
```heroku restart -a f-v2ray-2``` 重启应用，还是连接不上，隔一段时间在官网上还是看到服务挂掉了。

**Comment by iatomato** [comment]
我分析了超久，从昨天开始掉了

**Comment by iatomato** [comment]
。

**Comment by gittig11** [comment]
v2rayN客户端显示的报错：
```bash
2021/06/19 14:04:59 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://f-v2ray-3.herokuapp.com/):  > read tcp 192.168.1.103:59548->52.200.31.227:443: wsarecv: An existing connection was forcibly closed by the remote host. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://f-v2ray-3.herokuapp.com/):  > read tcp 192.168.1.103:51091->3.219.126.122:443: wsarecv: An existing connection was forcibly closed by the remote host. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://f-v2ray-3.herokuapp.com/):  > read tcp 192.168.1.103:54062->107.20.205.67:443: wsarecv: An existing connection was forcibly closed by the remote host. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://f-v2ray-3.herokuapp.com/):  > read tcp 192.168.1.103:61199->52.200.31.227:443: wsarecv: An existing connection was forcibly closed by the remote host. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://f-v2ray-3.herokuapp.com/):  > read tcp 192.168.1.103:53781->3.219.126.122:443: wsarecv: An existing connection was forcibly closed by the remote host.] > v2ray.com/core/common/retry: all retry attempts failed
```

**Comment by impeiran** [comment]
同，无限accepted

**Comment by bclswl0827** [comment]
我还没测试，没时间

**Comment by bclswl0827** [comment]
> 我还没测试，没时间

刚刚测试了，部分新部署的应用，443 端口被阻断，可以试试接入 cloudflare 来中转，heroku 这边是没问题的

**Comment by bclswl0827** [comment]
> 2021.6.18发现，之前部署的v2ray应用连接不上，后来登录 [官网](https://dashboard.heroku.com/apps)，看到服务挂掉了。
> ![heroku](https://raw.githubusercontent.com/gittig11/pic-cloud-repo/main/heroku%E6%9C%8D%E5%8A%A1%E6%8C%82%E6%8E%89.png)
> `heroku logs` 查看日志未发现异常。
> `heroku restart -a f-v2ray-2` 重启应用，还是连接不上，隔一段时间在官网上还是看到服务挂掉了。

20 分钟应用无访问，会进入休眠状态，不是挂掉 😅

**Comment by iatomato** [comment]
> > 我还没测试，没时间
> 
> 刚刚粗略测试了下，部分新部署的应用，443 端口被阻断，可以试试接入 cloudflare 来中转，heroku 这边是没问题的

感觉还是。。。

**Comment by gittig11** [comment]
> > 我还没测试，没时间
> 
> 刚刚粗略测试了下，部分新部署的应用，443 端口被阻断，可以试试接入 cloudflare 来中转，heroku 这边是没问题的

@bclswl0827 是这个原因，加了 cloudflare 就可以访问了，大佬厉害！

**Comment by iatomato** [comment]
> > > 我还没测试，没时间
> > 
> > 
> > 刚刚粗略测试了下，部分新部署的应用，443 端口被阻断，可以试试接入 cloudflare 来中转，heroku 这边是没问题的
> 
> @bclswl0827 是这个原因，加了 cloudflare 就可以访问了，大佬厉害！

重新部署了吗？我 cf 还是阻断

**Comment by openwrt-try** [comment]
> > > 我还没测试，没时间
> > 
> > 
> > 刚刚粗略测试了下，部分新部署的应用，443 端口被阻断，可以试试接入 cloudflare 来中转，heroku 这边是没问题的
> 
> @bclswl0827 是这个原因，加了 cloudflare 就可以访问了，大佬厉害！

兄弟，是用worker做一个么？求指点

**Comment by bclswl0827** [comment]
> > > > 我还没测试，没时间
> > > 
> > > 
> > > 刚刚粗略测试了下，部分新部署的应用，443 端口被阻断，可以试试接入 cloudflare 来中转，heroku 这边是没问题的
> > 
> > 
> > @bclswl0827 是这个原因，加了 cloudflare 就可以访问了，大佬厉害！
> 
> 兄弟，是用worker做一个么？求指点

是的

**Comment by gittig11** [comment]
> > > > 我还没测试，没时间
> > > 
> > > 
> > > 刚刚粗略测试了下，部分新部署的应用，443 端口被阻断，可以试试接入 cloudflare 来中转，heroku 这边是没问题的
> > 
> > 
> > @bclswl0827 是这个原因，加了 cloudflare 就可以访问了，大佬厉害！
> 
> 兄弟，是用worker做一个么？求指点

使用 cloudflare worker 中转，参考代码：
```js
addEventListener("fetch", event => {
  let url = new URL(event.request.url);
  url.hostname = "xxx.herokuapp.com";
  let request = new Request(url, event.request);
  event.respondWith(fetch(request))
})
```

**Comment by openwrt-try** [comment]
感谢bclswl0827大佬和gittig11兄弟，已经成功
