### ISSUE TITLE
Item could not be created

### ISSUE THREAD

**Issue by bennazb** [bclswl0827/v2ray-heroku#62]
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

I cannot Deploy App  in heroku site.

**Comment by bclswl0827** [comment]
Solution has been given in README.md, thanks for the feedback.

**Comment by JGuanJ** [comment]
你好，我也遇到同样的问题，请问我该如何“修改 README.md 中的部署链接为自己的用户名”？因为我刚接触Github不久，不太懂操作，抱歉！

**Comment by bclswl0827** [comment]
In `README.md`:

```
[![Deploy](https://www.herokucdn.com/deploy/button.png)](https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Fbclswl0827%2Fv2ray-heroku)
```

Just replace the username `bclswl0827` with yours.

**Comment by JGuanJ** [comment]
谢谢
