### ISSUE TITLE
v2ctl是否多余？

### ISSUE THREAD

**Issue by YulinChan** [bclswl0827/v2ray-heroku#63]
解压提取出来了v2ray、v2ctl两个可执行文件，但是脚本中只用到了v2ray而已，v2ctl是否多余？

**Comment by bclswl0827** [comment]
可以先用 `v2ctl` 将 `config.json` 转换为 Protobuf 格式的配置（`config.pb`）
然后删除 `v2ctl`，最后让 `v2ray` 直接读取 `config.pb`

```
$ ./v2ctl config < ./config.json > ./config.pb
$ rm -rf ./v2ctl ./*.pb
$ ./v2ray -config=./config.pb
```

**Comment by YulinChan** [comment]
哦，原来是这样子，查了一下，Protobuf比JSON性能更好。
但脚本代码中貌似还没实现，v2ctl安装后就没后续了。

**Comment by YulinChan** [comment]
> $ rm -rf ./v2ctl ./*.pb
这个命令因该是 `rm -rf ./v2ctl ./*.json 吧

**Comment by bclswl0827** [comment]
> 
> 
> > $ rm -rf ./v2ctl ./*.pb
> 
> 这个命令因该是 `rm -rf ./v2ctl ./*.json` 吧

不好意思，笔误

**Comment by bclswl0827** [comment]
https://github.com/bclswl0827/v2ray-heroku/commit/b059de99d9fb6a5097ecb48b8fa6b882ed62147b
