### ISSUE TITLE
该项目似乎已经被heroku封禁

### ISSUE THREAD

**Issue by DiamondUser** [bclswl0827/v2ray-heroku#64]
Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.
![屏幕截图_2021-07-02_20-51-21](https://user-images.githubusercontent.com/64264689/124277375-8e4e0100-db77-11eb-9c69-01be6b26ad89.png)

**Comment by bclswl0827** [comment]
See https://github.com/bclswl0827/v2ray-heroku/issues/62
Solution was given in README
