### ISSUE TITLE
添加ca-certificates的作用？

### ISSUE THREAD

**Issue by YulinChan** [bclswl0827/v2ray-heroku#66]
我看v2ray的官方安装脚本里没有用到其他依赖，也只是将v2ray、v2ctl及配置文件解压出来放到特定的位置而已。

所以，添加这个ca-certificates的作用是什么呢？是提供tls所需的接口或依赖？

ps:

我部署的时候没有用 `ca-certificates`，运行起来感觉还是一样的效果, 下面是我改的dockerfile的配置

```
FROM alpine:latest
ADD configure.sh /configure.sh
RUN chmod +x /configure.sh
CMD /configure.sh
```

**Comment by bclswl0827** [comment]
ca-certificates 包含了一系列根证书。Alpine Linux 中没有内建根证书，若无 ca-certificates ，下载 V2Ray 时可能出现错误。
