### ISSUE TITLE
你好，项目是不是不能用了，客户端连接不上

### ISSUE THREAD

**Issue by jack01-make** [bclswl0827/v2ray-heroku#7]

**Comment by bclswl0827** [comment]
老哥，这个一直可以用的哦

**Comment by jack01-make** [comment]
好的，十分感谢，我再试试看。感谢开发者！辛苦了！

**Comment by jack01-make** [comment]
2020/03/07 12:19:19 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://https://hehheei.herokuapp.com//):  > dial tcp: address https://hehheei.herokuapp.com/:443: too many colons in address] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by jack01-make** [comment]
我试了一早上，客户端的日志是这样的，一直ping不通。我哪里弄错了吗

**Comment by xoraxrax** [comment]
新建的也ping不同

**Comment by bclswl0827** [comment]
> https://hehheei.herokuapp.com/

注意你地址填错了，服务器域名不应该带有 HTTPS://

这个项目正常的

**Comment by bclswl0827** [comment]
> 新建的也ping不同

ping 值不能说明问题

**Comment by jack01-make** [comment]
没错，确实可以用。为什么不加Https呢？

**Comment by opksha** [comment]
> > https://hehheei.herokuapp.com/
> 
> 注意你地址填错了，服务器域名不应该带有 HTTPS://
> 
> 这个项目正常的

![image](https://user-images.githubusercontent.com/27957496/76703638-e99f7a00-670d-11ea-860a-5eb2ef6c30d0.png)
这个是我的配置 连不上 之前也是这样的可以连

**Comment by bclswl0827** [comment]
> > > https://hehheei.herokuapp.com/
> > 
> > 
> > 注意你地址填错了，服务器域名不应该带有 HTTPS://
> > 这个项目正常的
> 
> ![image](https://user-images.githubusercontent.com/27957496/76703638-e99f7a00-670d-11ea-860a-5eb2ef6c30d0.png)
> 这个是我的配置 连不上 之前也是这样的可以连

伪装域名去掉

**Comment by opksha** [comment]
我第一次创建的能用 
![image](https://user-images.githubusercontent.com/27957496/76770017-3cddff00-67d8-11ea-856e-14c9cf5e8f86.png)
然后给我暂停了 其实我没怎么连 是打算备用的 然后创建第二个 刚创建时连着用了以下 然后放在哪 后来再连就连不上  就删了
前俩天创建第三个 就是这个  我刚把`伪装域名`删了还是不行 估计给我账号禁止了

**Comment by firstwaterer** [comment]
可不可以 在Heroku开发 VLESS+TCP+xtls-rprx-direct或 VLESS+TCP+xtls-rprx-origin，guy
