### ISSUE TITLE
部署后显示Applicaton Error

### ISSUE THREAD

**Issue by DiamondUser** [bclswl0827/v2ray-heroku#70]
视频
https://diamonduser303-my.sharepoint.com/:v:/g/personal/diamonduser303_diamonduser303_onmicrosoft_com/EbOyVckGyL9OlJoX2yukx-wB9bNDmpdHU6aOEmjqQzLIcA?e=0KkU3n

**Comment by bclswl0827** [comment]
烦请提供应用日志

**Comment by DiamondUser** [comment]
[v2ray-diamonduser-logs-1625567632601.txt](https://github.com/bclswl0827/v2ray-heroku/files/6769327/v2ray-diamonduser-logs-1625567632601.txt)

**Comment by bclswl0827** [comment]
唤起应用时，`curl` 没有成功从 `https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip` 拉取 V2Ray 可执行文件。
这份日志没有关于 `curl` 部分的报错，所以也不清楚具体是什么原因造成的

> 
> 
> [v2ray-diamonduser-logs-1625567632601.txt](https://github.com/bclswl0827/v2ray-heroku/files/6769327/v2ray-diamonduser-logs-1625567632601.txt)

**Comment by DiamondUser** [comment]
我是先将您的项目fork后，将部署链接中的bclswl0827修改成我的Github用户名，此过程是否有错误？

**Comment by bclswl0827** [comment]
> 我是先将您的项目fork后，将部署链接中的bclswl0827修改成我的Github用户名，此过程是否有错误？

无误，这个不影响的

**Comment by DiamondUser** [comment]
好的谢谢您

**Comment by a114426** [comment]
你解决了吗?

**Comment by bclswl0827** [comment]
已经更新 https://github.com/bclswl0827/v2ray-heroku/commit/b059de99d9fb6a5097ecb48b8fa6b882ed62147b
请重新 Fork 后再部署

**Comment by DiamondUser** [comment]
感谢，已经解决:)
