### ISSUE TITLE
请问如何部署v2+ws+tls+cdn

### ISSUE THREAD

**Issue by ktownag** [bclswl0827/v2ray-heroku#8]
刚需。请大神指教。脚本指定域名部署以后无法连接，是不是需要安装证书？

**Comment by GHinStyle** [comment]
https://support.cloudflare.com/hc/zh-cn/articles/205893698-%E9%80%9A%E8%BF%87-HTTPS-%E9%85%8D%E7%BD%AE-Cloudflare-%E5%92%8C-Heroku
请 **仔细** 看这篇文章

**Comment by ktownag** [comment]
谢谢~
